### ISSUE TITLE
Doubt regarding early-return.py example

### ISSUE THREAD

**Issue by ju-sh** [nickboucher/trojan-source#22]
In the [early-return.py](https://github.com/nickboucher/trojan-source/blob/main/Python/early-return.py?h=1) example, I had thought

```
then <RLI> ''' ;return
```

would end up being rendered as

```
then nruter; '''
```

where every character from the end of line (there's an implicit `<PDI>` at end of line, right? Or doesn't this end of line not count as an end of paragraph?) to the `<RLI>` are displayed one by one.

But I suppose that's not how it works since it gets displayed as

```
then return; '''
```

Could someone help me understand this?

**Comment by ju-sh** [comment]
Found an example [here](https://unicode.org/reports/tr9/#Basic_Display_Algorithm) that says:

```
Memory:  he said "<RLI>I NEED WATER!<PDI>", and expired.
Display: he said "!RETAW DEEN I", and expired.
```

But does it work differently in the early-return example?

**Comment by nickboucher** [comment]
This is a great point -- the RLI character behaves strangely. The example that you reference comes from the de facto source of truth for a correct Unicode implementation, but that's not the behavior that I observe in practice.

Unicode Bidi implementations differ by application & OS, but rendering "<RLI>I NEED WATER!<PDI>" in Chromium-based browsers for me yields something that looks like "!I NEED WATER". For comparison, here's the encoded form for anyone reading to observe in their own browser:
```
⁧I NEED WATER!⁩
```

Experimentally, it appears to me that (at least in Chromium-based software) RLI affects [neutral characters](https://en.wikipedia.org/wiki/Bidirectional_text#Neutral_characters) but not [strong characters](https://en.wikipedia.org/wiki/Bidirectional_text#Strong_characters); or, rather, at least affects neutral and strong characters differently.

It's not immediately clear to me whether this behavior is in the Unicode Bidi spec, or whether this is a bug/undefined behavior in specific Bidi implementations.

**Comment by ju-sh** [comment]
Thanks. I think in the example from the page for the bidi algorithm, they use upper case characters as a kind of notation to represent a script written from right to left (or something like that).

And do you know how is bidi pronounced? Is it 'by-dye' or 'bee-dee'?

**Comment by nickboucher** [comment]
I've heard it pronounced many different ways; I'm not sure that there's a consensus. Although it's a different "Bidirectional" there's a related thread about it [here](https://www.reddit.com/r/networking/comments/3czyqv/how_do_you_pronounce_bidi/).
